#!/bin/bash
# brightness -- controls laptop brightness hopefully
monitor="acpi_video0" # look in /sys/class/backlight/


for h in "$1";do
    case "$derp" in 
        current)
        cat "/sys/class/backlight/$monitor/brightness"
        ;;
        up)
        echo "$(( $(cat /sys/class/backlight/$monitor/  brightness) + 1 ))" > "$HOME/.$$-brightness"
        sudo bash -c "cat '$HOME/.$$-brightness' > /sys/class/backlight/$monitor/brightness"
        ;;
        down)
        echo "$(( $(cat /sys/class/backlight/$monitor/brightness) - 1 ))" > "$HOME/.$$-brightness"
        sudo bash -c "cat '$HOME/.$$-brightness' > /sys/class/backlight/$monitor/brightness"
        ;;
        set)
        echo "$2" > "$HOME/.$$-brightness"
        sudo bash -c "cat '$HOME/.$$-brightness' > /sys/class/backlight/$monitor/brightness"
        ;;
        help|*)
        echo "Usage: ${0##*/} [action] [amount]"
        echo "\tcurrent: tells current brightness level"
        echo "\tup: increments brightness level by one"
        echo "\tdown: reduces brightness level by one"
        echo "\tset: sets brightness level to [amount]"
        ;;
    esac
    rm -vrf "$HOME/.$$-brightness" >/dev/null
done
