#!/bin/bash
# jimmies -- that really rustles my jimmies

if [[ "$1" == "all" ]];then
    word1=$(shuf /usr/share/dict/* 2>/dev/null | grep 'es$' 2>/dev/null | tr '[A-Z]' '[a-z]' 2>/dev/null | head -n 1 2>/dev/null)
    word2=$(shuf /usr/share/dict/* 2>/dev/null | grep 'es$' 2>/dev/null | tr '[A-Z]' '[a-z]' 2>/dev/null | head -n 1 2>/dev/null)
else
    word1=$(shuf /usr/share/dict/words 2>/dev/null | grep 'es$' 2>/dev/null | tr '[A-Z]' '[a-z]' 2>/dev/null | head -n 1 2>/dev/null)
    word2=$(shuf /usr/share/dict/words 2>/dev/null | grep 'ies$' 2>/dev/null | tr '[A-Z]' '[a-z]' 2>/dev/null | head -n 1 2>/dev/null)
fi
echo "That really $word1 my $word2."

